;; Physical constants in the CGSM system
;; Liam Healy 2009-05-25 17:01:32EDT cgsm.lisp
;; Time-stamp: <2009-05-28 23:01:08EDT cgsm.lisp>
;; $Id: $

#+linux
(define "_GNU_SOURCE")

(in-package :gsl)

(include "gsl/gsl_const_cgsm.h")

(constant (+cgsm-speed-of-light+ "GSL_CONST_CGSM_SPEED_OF_LIGHT") :format "D")
(constant (+cgsm-gravitational-constant+ "GSL_CONST_CGSM_GRAVITATIONAL_CONSTANT")
	  :format "D")
(constant (+cgsm-plancks-constant-h+ GSL_CONST_CGSM_PLANCKS_CONSTANT_H)
	  :format "D")
(constant (+cgsm-plancks-constant-hbar+ GSL_CONST_CGSM_PLANCKS_CONSTANT_HBAR)
	  :format "D")
(constant (+cgsm-astronomical-unit+ GSL_CONST_CGSM_ASTRONOMICAL_UNIT) :format "D")
(constant (+cgsm-light-year+ GSL_CONST_CGSM_LIGHT_YEAR) :format "D")
(constant (+cgsm-parsec+ GSL_CONST_CGSM_PARSEC) :format "D")
(constant (+cgsm-grav-accel+ GSL_CONST_CGSM_GRAV_ACCEL) :format "D")
(constant (+cgsm-electron-volt+ GSL_CONST_CGSM_ELECTRON_VOLT) :format "D")
(constant (+cgsm-mass-electron+ GSL_CONST_CGSM_MASS_ELECTRON) :format "D")
(constant (+cgsm-mass-muon+ GSL_CONST_CGSM_MASS_MUON) :format "D")
(constant (+cgsm-mass-proton+ GSL_CONST_CGSM_MASS_PROTON) :format "D")
(constant (+cgsm-mass-neutron+ GSL_CONST_CGSM_MASS_NEUTRON) :format "D")
(constant (+cgsm-rydberg+ GSL_CONST_CGSM_RYDBERG) :format "D")
(constant (+cgsm-boltzmann+ GSL_CONST_CGSM_BOLTZMANN) :format "D")
(constant (+cgsm-bohr-magneton+ GSL_CONST_CGSM_BOHR_MAGNETON) :format "D")
(constant (+cgsm-nuclear-magneton+ GSL_CONST_CGSM_NUCLEAR_MAGNETON) :format "D")
(constant (+cgsm-electron-magnetic-moment+ GSL_CONST_CGSM_ELECTRON_MAGNETIC_MOMENT)
	  :format "D")
(constant (+cgsm-proton-magnetic-moment+ GSL_CONST_CGSM_PROTON_MAGNETIC_MOMENT)
	  :format "D")
(constant (+cgsm-molar-gas+ GSL_CONST_CGSM_MOLAR_GAS) :format "D")
(constant (+cgsm-standard-gas-volume+ GSL_CONST_CGSM_STANDARD_GAS_VOLUME) :format "D")
(constant (+cgsm-minute+ GSL_CONST_CGSM_MINUTE) :format "D")
(constant (+cgsm-hour+ GSL_CONST_CGSM_HOUR) :format "D")
(constant (+cgsm-day+ GSL_CONST_CGSM_DAY) :format "D")
(constant (+cgsm-week+ GSL_CONST_CGSM_WEEK) :format "D")
(constant (+cgsm-inch+ GSL_CONST_CGSM_INCH) :format "D")
(constant (+cgsm-foot+ GSL_CONST_CGSM_FOOT) :format "D")
(constant (+cgsm-yard+ GSL_CONST_CGSM_YARD) :format "D")
(constant (+cgsm-mile+ GSL_CONST_CGSM_MILE) :format "D")
(constant (+cgsm-nautical-mile+ GSL_CONST_CGSM_NAUTICAL_MILE) :format "D")
(constant (+cgsm-fathom+ GSL_CONST_CGSM_FATHOM) :format "D")
(constant (+cgsm-mil+ GSL_CONST_CGSM_MIL) :format "D")
(constant (+cgsm-point+ GSL_CONST_CGSM_POINT) :format "D")
(constant (+cgsm-texpoint+ GSL_CONST_CGSM_TEXPOINT) :format "D")
(constant (+cgsm-micron+ GSL_CONST_CGSM_MICRON) :format "D")
(constant (+cgsm-angstrom+ GSL_CONST_CGSM_ANGSTROM) :format "D")
(constant (+cgsm-hectare+ GSL_CONST_CGSM_HECTARE) :format "D")
(constant (+cgsm-acre+ GSL_CONST_CGSM_ACRE) :format "D")
(constant (+cgsm-barn+ GSL_CONST_CGSM_BARN) :format "D")
(constant (+cgsm-liter+ GSL_CONST_CGSM_LITER) :format "D")
(constant (+cgsm-us-gallon+ GSL_CONST_CGSM_US_GALLON) :format "D")
(constant (+cgsm-quart+ GSL_CONST_CGSM_QUART) :format "D")
(constant (+cgsm-pint+ GSL_CONST_CGSM_PINT) :format "D")
(constant (+cgsm-cup+ GSL_CONST_CGSM_CUP) :format "D")
(constant (+cgsm-fluid-ounce+ GSL_CONST_CGSM_FLUID_OUNCE) :format "D")
(constant (+cgsm-tablespoon+ GSL_CONST_CGSM_TABLESPOON) :format "D")
(constant (+cgsm-teaspoon+ GSL_CONST_CGSM_TEASPOON) :format "D")
(constant (+cgsm-canadian-gallon+ GSL_CONST_CGSM_CANADIAN_GALLON) :format "D")
(constant (+cgsm-uk-gallon+ GSL_CONST_CGSM_UK_GALLON) :format "D")
(constant (+cgsm-miles-per-hour+ GSL_CONST_CGSM_MILES_PER_HOUR) :format "D")
(constant (+cgsm-kilometers-per-hour+ GSL_CONST_CGSM_KILOMETERS_PER_HOUR)
	  :format "D")
(constant (+cgsm-knot+ GSL_CONST_CGSM_KNOT) :format "D")
(constant (+cgsm-pound-mass+ GSL_CONST_CGSM_POUND_MASS) :format "D")
(constant (+cgsm-ounce-mass+ GSL_CONST_CGSM_OUNCE_MASS) :format "D")
(constant (+cgsm-ton+ GSL_CONST_CGSM_TON) :format "D")
(constant (+cgsm-metric-ton+ GSL_CONST_CGSM_METRIC_TON) :format "D")
(constant (+cgsm-uk-ton+ GSL_CONST_CGSM_UK_TON) :format "D")
(constant (+cgsm-troy-ounce+ GSL_CONST_CGSM_TROY_OUNCE) :format "D")
(constant (+cgsm-carat+ GSL_CONST_CGSM_CARAT) :format "D")
(constant (+cgsm-unified-atomic-mass+ GSL_CONST_CGSM_UNIFIED_ATOMIC_MASS)
	  :format "D")
(constant (+cgsm-gram-force+ GSL_CONST_CGSM_GRAM_FORCE) :format "D")
(constant (+cgsm-pound-force+ GSL_CONST_CGSM_POUND_FORCE) :format "D")
(constant (+cgsm-kilopound-force+ GSL_CONST_CGSM_KILOPOUND_FORCE) :format "D")
(constant (+cgsm-poundal+ GSL_CONST_CGSM_POUNDAL) :format "D")
(constant (+cgsm-calorie+ GSL_CONST_CGSM_CALORIE) :format "D")
(constant (+cgsm-btu+ GSL_CONST_CGSM_BTU) :format "D")
(constant (+cgsm-therm+ GSL_CONST_CGSM_THERM) :format "D")
(constant (+cgsm-horsepower+ GSL_CONST_CGSM_HORSEPOWER) :format "D")
(constant (+cgsm-bar+ GSL_CONST_CGSM_BAR) :format "D")
(constant (+cgsm-std-atmosphere+ GSL_CONST_CGSM_STD_ATMOSPHERE) :format "D")
(constant (+cgsm-torr+ GSL_CONST_CGSM_TORR) :format "D")
(constant (+cgsm-meter-of-mercury+ GSL_CONST_CGSM_METER_OF_MERCURY)
	  :format "D")
(constant (+cgsm-inch-of-mercury+ GSL_CONST_CGSM_INCH_OF_MERCURY) :format "D")
(constant (+cgsm-inch-of-water+ GSL_CONST_CGSM_INCH_OF_WATER) :format "D")
(constant (+cgsm-psi+ GSL_CONST_CGSM_PSI) :format "D")
(constant (+cgsm-poise+ GSL_CONST_CGSM_POISE) :format "D")
(constant (+cgsm-stokes+ GSL_CONST_CGSM_STOKES) :format "D")
(constant (+cgsm-faraday+ GSL_CONST_CGSM_FARADAY) :format "D")
(constant (+cgsm-electron-charge+ GSL_CONST_CGSM_ELECTRON_CHARGE) :format "D")
(constant (+cgsm-gauss+ GSL_CONST_CGSM_GAUSS) :format "D")
(constant (+cgsm-stilb+ GSL_CONST_CGSM_STILB) :format "D")
(constant (+cgsm-lumen+ GSL_CONST_CGSM_LUMEN) :format "D")
(constant (+cgsm-lux+ GSL_CONST_CGSM_LUX) :format "D")
(constant (+cgsm-phot+ GSL_CONST_CGSM_PHOT) :format "D")
(constant (+cgsm-footcandle+ GSL_CONST_CGSM_FOOTCANDLE) :format "D")
(constant (+cgsm-lambert+ GSL_CONST_CGSM_LAMBERT) :format "D")
(constant (+cgsm-footlambert+ GSL_CONST_CGSM_FOOTLAMBERT) :format "D")
(constant (+cgsm-curie+ GSL_CONST_CGSM_CURIE) :format "D")
(constant (+cgsm-roentgen+ GSL_CONST_CGSM_ROENTGEN) :format "D")
(constant (+cgsm-rad+ GSL_CONST_CGSM_RAD) :format "D")
(constant (+cgsm-solar-mass+ GSL_CONST_CGSM_SOLAR_MASS) :format "D")
(constant (+cgsm-bohr-radius+ GSL_CONST_CGSM_BOHR_RADIUS) :format "D")
(constant (+cgsm-newton+ GSL_CONST_CGSM_NEWTON) :format "D")
(constant (+cgsm-dyne+ GSL_CONST_CGSM_DYNE) :format "D")
(constant (+cgsm-joule+ GSL_CONST_CGSM_JOULE) :format "D")
(constant (+cgsm-erg+ GSL_CONST_CGSM_ERG) :format "D")
(constant (+cgsm-stefan-boltzmann-constant+
	   GSL_CONST_CGSM_STEFAN_BOLTZMANN_CONSTANT)
	  :format "D")
(constant (+cgsm-thomson-cross-section+ GSL_CONST_CGSM_THOMSON_CROSS_SECTION)
	  :format "D")
