;; Physical constants in the MKSA system
;; Liam Healy 2009-05-25 17:01:32EDT mksa.lisp
;; Time-stamp: <2009-05-28 22:35:46EDT mksa.lisp>
;; $Id: $

#+linux
(define "_GNU_SOURCE")

(in-package :gsl)

(include "gsl/gsl_const_mksa.h")

(constant (+mksa-speed-of-light+ "GSL_CONST_MKSA_SPEED_OF_LIGHT") :format "D")
(constant (+mksa-gravitational-constant+ "GSL_CONST_MKSA_GRAVITATIONAL_CONSTANT")
	  :format "D")
(constant (+mksa-plancks-constant-h+ GSL_CONST_MKSA_PLANCKS_CONSTANT_H)
	  :format "D")
(constant (+mksa-plancks-constant-hbar+ GSL_CONST_MKSA_PLANCKS_CONSTANT_HBAR)
	  :format "D")
(constant (+mksa-astronomical-unit+ GSL_CONST_MKSA_ASTRONOMICAL_UNIT) :format "D")
(constant (+mksa-light-year+ GSL_CONST_MKSA_LIGHT_YEAR) :format "D")
(constant (+mksa-parsec+ GSL_CONST_MKSA_PARSEC) :format "D")
(constant (+mksa-grav-accel+ GSL_CONST_MKSA_GRAV_ACCEL) :format "D")
(constant (+mksa-electron-volt+ GSL_CONST_MKSA_ELECTRON_VOLT) :format "D")
(constant (+mksa-mass-electron+ GSL_CONST_MKSA_MASS_ELECTRON) :format "D")
(constant (+mksa-mass-muon+ GSL_CONST_MKSA_MASS_MUON) :format "D")
(constant (+mksa-mass-proton+ GSL_CONST_MKSA_MASS_PROTON) :format "D")
(constant (+mksa-mass-neutron+ GSL_CONST_MKSA_MASS_NEUTRON) :format "D")
(constant (+mksa-rydberg+ GSL_CONST_MKSA_RYDBERG) :format "D")
(constant (+mksa-boltzmann+ GSL_CONST_MKSA_BOLTZMANN) :format "D")
(constant (+mksa-bohr-magneton+ GSL_CONST_MKSA_BOHR_MAGNETON) :format "D")
(constant (+mksa-nuclear-magneton+ GSL_CONST_MKSA_NUCLEAR_MAGNETON) :format "D")
(constant (+mksa-electron-magnetic-moment+ GSL_CONST_MKSA_ELECTRON_MAGNETIC_MOMENT)
	  :format "D")
(constant (+mksa-proton-magnetic-moment+ GSL_CONST_MKSA_PROTON_MAGNETIC_MOMENT)
	  :format "D")
(constant (+mksa-molar-gas+ GSL_CONST_MKSA_MOLAR_GAS) :format "D")
(constant (+mksa-standard-gas-volume+ GSL_CONST_MKSA_STANDARD_GAS_VOLUME) :format "D")
(constant (+mksa-minute+ GSL_CONST_MKSA_MINUTE) :format "D")
(constant (+mksa-hour+ GSL_CONST_MKSA_HOUR) :format "D")
(constant (+mksa-day+ GSL_CONST_MKSA_DAY) :format "D")
(constant (+mksa-week+ GSL_CONST_MKSA_WEEK) :format "D")
(constant (+mksa-inch+ GSL_CONST_MKSA_INCH) :format "D")
(constant (+mksa-foot+ GSL_CONST_MKSA_FOOT) :format "D")
(constant (+mksa-yard+ GSL_CONST_MKSA_YARD) :format "D")
(constant (+mksa-mile+ GSL_CONST_MKSA_MILE) :format "D")
(constant (+mksa-nautical-mile+ GSL_CONST_MKSA_NAUTICAL_MILE) :format "D")
(constant (+mksa-fathom+ GSL_CONST_MKSA_FATHOM) :format "D")
(constant (+mksa-mil+ GSL_CONST_MKSA_MIL) :format "D")
(constant (+mksa-point+ GSL_CONST_MKSA_POINT) :format "D")
(constant (+mksa-texpoint+ GSL_CONST_MKSA_TEXPOINT) :format "D")
(constant (+mksa-micron+ GSL_CONST_MKSA_MICRON) :format "D")
(constant (+mksa-angstrom+ GSL_CONST_MKSA_ANGSTROM) :format "D")
(constant (+mksa-hectare+ GSL_CONST_MKSA_HECTARE) :format "D")
(constant (+mksa-acre+ GSL_CONST_MKSA_ACRE) :format "D")
(constant (+mksa-barn+ GSL_CONST_MKSA_BARN) :format "D")
(constant (+mksa-liter+ GSL_CONST_MKSA_LITER) :format "D")
(constant (+mksa-us-gallon+ GSL_CONST_MKSA_US_GALLON) :format "D")
(constant (+mksa-quart+ GSL_CONST_MKSA_QUART) :format "D")
(constant (+mksa-pint+ GSL_CONST_MKSA_PINT) :format "D")
(constant (+mksa-cup+ GSL_CONST_MKSA_CUP) :format "D")
(constant (+mksa-fluid-ounce+ GSL_CONST_MKSA_FLUID_OUNCE) :format "D")
(constant (+mksa-tablespoon+ GSL_CONST_MKSA_TABLESPOON) :format "D")
(constant (+mksa-teaspoon+ GSL_CONST_MKSA_TEASPOON) :format "D")
(constant (+mksa-canadian-gallon+ GSL_CONST_MKSA_CANADIAN_GALLON) :format "D")
(constant (+mksa-uk-gallon+ GSL_CONST_MKSA_UK_GALLON) :format "D")
(constant (+mksa-miles-per-hour+ GSL_CONST_MKSA_MILES_PER_HOUR) :format "D")
(constant (+mksa-kilometers-per-hour+ GSL_CONST_MKSA_KILOMETERS_PER_HOUR)
	  :format "D")
(constant (+mksa-knot+ GSL_CONST_MKSA_KNOT) :format "D")
(constant (+mksa-pound-mass+ GSL_CONST_MKSA_POUND_MASS) :format "D")
(constant (+mksa-ounce-mass+ GSL_CONST_MKSA_OUNCE_MASS) :format "D")
(constant (+mksa-ton+ GSL_CONST_MKSA_TON) :format "D")
(constant (+mksa-metric-ton+ GSL_CONST_MKSA_METRIC_TON) :format "D")
(constant (+mksa-uk-ton+ GSL_CONST_MKSA_UK_TON) :format "D")
(constant (+mksa-troy-ounce+ GSL_CONST_MKSA_TROY_OUNCE) :format "D")
(constant (+mksa-carat+ GSL_CONST_MKSA_CARAT) :format "D")
(constant (+mksa-unified-atomic-mass+ GSL_CONST_MKSA_UNIFIED_ATOMIC_MASS)
	  :format "D")
(constant (+mksa-gram-force+ GSL_CONST_MKSA_GRAM_FORCE) :format "D")
(constant (+mksa-pound-force+ GSL_CONST_MKSA_POUND_FORCE) :format "D")
(constant (+mksa-kilopound-force+ GSL_CONST_MKSA_KILOPOUND_FORCE) :format "D")
(constant (+mksa-poundal+ GSL_CONST_MKSA_POUNDAL) :format "D")
(constant (+mksa-calorie+ GSL_CONST_MKSA_CALORIE) :format "D")
(constant (+mksa-btu+ GSL_CONST_MKSA_BTU) :format "D")
(constant (+mksa-therm+ GSL_CONST_MKSA_THERM) :format "D")
(constant (+mksa-horsepower+ GSL_CONST_MKSA_HORSEPOWER) :format "D")
(constant (+mksa-bar+ GSL_CONST_MKSA_BAR) :format "D")
(constant (+mksa-std-atmosphere+ GSL_CONST_MKSA_STD_ATMOSPHERE) :format "D")
(constant (+mksa-torr+ GSL_CONST_MKSA_TORR) :format "D")
(constant (+mksa-meter-of-mercury+ GSL_CONST_MKSA_METER_OF_MERCURY)
	  :format "D")
(constant (+mksa-inch-of-mercury+ GSL_CONST_MKSA_INCH_OF_MERCURY) :format "D")
(constant (+mksa-inch-of-water+ GSL_CONST_MKSA_INCH_OF_WATER) :format "D")
(constant (+mksa-psi+ GSL_CONST_MKSA_PSI) :format "D")
(constant (+mksa-poise+ GSL_CONST_MKSA_POISE) :format "D")
(constant (+mksa-stokes+ GSL_CONST_MKSA_STOKES) :format "D")
(constant (+mksa-faraday+ GSL_CONST_MKSA_FARADAY) :format "D")
(constant (+mksa-electron-charge+ GSL_CONST_MKSA_ELECTRON_CHARGE) :format "D")
(constant (+mksa-gauss+ GSL_CONST_MKSA_GAUSS) :format "D")
(constant (+mksa-stilb+ GSL_CONST_MKSA_STILB) :format "D")
(constant (+mksa-lumen+ GSL_CONST_MKSA_LUMEN) :format "D")
(constant (+mksa-lux+ GSL_CONST_MKSA_LUX) :format "D")
(constant (+mksa-phot+ GSL_CONST_MKSA_PHOT) :format "D")
(constant (+mksa-footcandle+ GSL_CONST_MKSA_FOOTCANDLE) :format "D")
(constant (+mksa-lambert+ GSL_CONST_MKSA_LAMBERT) :format "D")
(constant (+mksa-footlambert+ GSL_CONST_MKSA_FOOTLAMBERT) :format "D")
(constant (+mksa-curie+ GSL_CONST_MKSA_CURIE) :format "D")
(constant (+mksa-roentgen+ GSL_CONST_MKSA_ROENTGEN) :format "D")
(constant (+mksa-rad+ GSL_CONST_MKSA_RAD) :format "D")
(constant (+mksa-solar-mass+ GSL_CONST_MKSA_SOLAR_MASS) :format "D")
(constant (+mksa-bohr-radius+ GSL_CONST_MKSA_BOHR_RADIUS) :format "D")
(constant (+mksa-newton+ GSL_CONST_MKSA_NEWTON) :format "D")
(constant (+mksa-dyne+ GSL_CONST_MKSA_DYNE) :format "D")
(constant (+mksa-joule+ GSL_CONST_MKSA_JOULE) :format "D")
(constant (+mksa-erg+ GSL_CONST_MKSA_ERG) :format "D")
(constant (+mksa-stefan-boltzmann-constant+
	   GSL_CONST_MKSA_STEFAN_BOLTZMANN_CONSTANT)
	  :format "D")
(constant (+mksa-thomson-cross-section+ GSL_CONST_MKSA_THOMSON_CROSS_SECTION)
	  :format "D")
(constant (+mksa-vacuum-permittivity+ GSL_CONST_MKSA_VACUUM_PERMITTIVITY)
	  :format "D")
(constant (+mksa-vacuum-permeability+ GSL_CONST_MKSA_VACUUM_PERMEABILITY)
	  :format "D")
(constant (+mksa-debye+ GSL_CONST_MKSA_DEBYE) :format "D")
